// Code generated by MockGen. DO NOT EDIT.
// Source: lesson_4/email.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIEmailGateway is a mock of IEmailGateway interface
type MockIEmailGateway struct {
	ctrl     *gomock.Controller
	recorder *MockIEmailGatewayMockRecorder
}

// MockIEmailGatewayMockRecorder is the mock recorder for MockIEmailGateway
type MockIEmailGatewayMockRecorder struct {
	mock *MockIEmailGateway
}

// NewMockIEmailGateway creates a new mock instance
func NewMockIEmailGateway(ctrl *gomock.Controller) *MockIEmailGateway {
	mock := &MockIEmailGateway{ctrl: ctrl}
	mock.recorder = &MockIEmailGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEmailGateway) EXPECT() *MockIEmailGatewayMockRecorder {
	return m.recorder
}

// SendGreetingsEmail mocks base method
func (m *MockIEmailGateway) SendGreetingsEmail(email string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendGreetingsEmail", email)
}

// SendGreetingsEmail indicates an expected call of SendGreetingsEmail
func (mr *MockIEmailGatewayMockRecorder) SendGreetingsEmail(email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendGreetingsEmail", reflect.TypeOf((*MockIEmailGateway)(nil).SendGreetingsEmail), email)
}
